DepositsIntegrationService/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('webapp.urls'))
]

webapp/urls.py
from django.conf.urls.static import static
from django.urls import path, include
from django.views.generic import TemplateView

from . import views


app_name = 'webapp'

urlpatterns = [
    path('', views.UserLogin, name='login'),
    path('history/',views.transaction_history, name='transaction-history'),
    path('account_number/',views.checkAccNumber,name='check-account-number'),
    path('bank_details/upload/verify_account/zicb/',views.zicb_customer_account_number_check),
    path('bank_details/upload/verify_account/other/', views.other_bank_account_number_check),
    path('enter_otp/',views.enterOTP, name = 'enter-otp'),
    path('forgot_password',views.forgotPassword, name = 'forgot-password'),
    path('role/', views.checkUserRole),
    path('account_details/', views.vendor_account_details),
    path('dashboard',views.homepage, name='homepage'),
    path('bank_details/edit/<str:acc_id>/',views.editBankUploadViaForm,name='edit-bank-details'),
    path('bank_details/upload/',views.bankUploadViaForm, name='upload-bank-details'),
    path('bank_details/template/',views.bankUploadCSVTemplate,name='bank-details-template'),
    path('bank_details/upload/csv/',views.bankUploadCSV, name='upload-bank-details-csv'),
    path('bank_details',views.vendorBankDetails,name='bank-details'),
    path('bank_details/search/',views.searchvendorBankDetails,name='search-vendor-bank-details'),
    path('search/', views.get_search_results, name='search-transactions'),
    path('post-transactions/', views.post_transactions, name='post-transactions'),
    path('logout',views.UserLogout, name='logout'),
    path('search-invoices/', views.search_invoice_id, name='search-invoices'),
    path('bank_details/upload/loadBanks/',views.loadBankList),
    path('bank_details/delete/<str:acc_no>/', views.delete_vendor, name='delete'),

]

templates/account-details.html
{% extends 'base2.html' %}
{% load static %}
{% load widget_tweaks %}
{% block content %}

    <div class="formbold-main-wrapper">
        {% if messages %}
            {% for message in messages %}
                <p class="text-muted text-center"> {{ message }} </p>
            {% endfor %}
        {% endif %}

        <div class="formbold-form-wrapper">
            <form action="{% url 'webapp:upload-bank-details' %}" method="POST" id="bankDetailsForm">
                {% csrf_token %}
                <div class="formbold-form-title">
                    <h2 class="">Add Vendor Bank Details</h2>
                </div>
                <div class="formbold-input-flex">
                    <div id="vid" {% if form.vendor_id.errors %} class="error" {% endif %} hx-select="#vid"
                         hx-post="{% url 'webapp:upload-bank-details' %}"
                         hx-trigger="blur from:find input" hx-taget="#vid">
                        <label class="formbold-form-label"> {{ form.vendor_id.label }}</label>
                        {% render_field form.vendor_id type="text" name="vendor_id" id="vendorid" class="formbold-form-input" %}
                        {{ form.vendor_id.errors }}
                    </div>
                    <div id="vname" {% if form.account_name.errors %} class="error" {% endif %} hx-select="#accountname"
                         hx-post="{% url 'webapp:upload-bank-details' %}"
                         hx-trigger="blur from:find input" hx-taget="#accountname">
                        <label class="formbold-form-label"> {{ form.account_name.label }}</label>
                        {% render_field form.account_name type="text" name="account_name" id="accountname" class="formbold-form-input" %}
                        {{ form.account_name.errors }}
                    </div>

                </div>

                <div class="formbold-input-flex">
                    <div id="email" hx-select="#email"
                         hx-post="{% url 'webapp:upload-bank-details' %}"
                         hx-trigger="blur from:find input" hx-taget="#email">
                        <label class="formbold-form-label">{{ form.vendor_email.label }} </label>
                        {% render_field form.vendor_email type="text" name="vendor_email" id="vendoremail" class="formbold-form-input" %}
                        {{ form.vendor_email.errors }}
                    </div>
                    <div id="vmno" hx-select="#vmno" hx-post="{% url 'webapp:upload-bank-details' %}"
                         hx-trigger="blur from:find input" hx-taget="#vmno">
                        <label class="formbold-form-label">{{ form.vendor_mobile_number.label }}</label>
                        {% render_field form.vendor_mobile_number type="text" name="vendor_mobile_no" id="vendorphone" class="formbold-form-input" %}
                        {{ form.vendor_mobile_number.errors }}
                    </div>
                </div>

                <div class="formbold-input-flex" id="bank_dropdown">
                    <div>
                        <label class="formbold-form-label">Bank Name</label>
                        <select id="bankNameSelect" name="bank_name" class="form-select">
                            <option></option>
                            <option value="ZICB">ZICB</option>
                        </select>
                    </div>
                    <div id="acc_if_zicb" class="d-none" {% if form.account_no.errors %} class="error" {% endif %}>
                        <label class="formbold-form-label">{{ form.account_no.label }} </label>
                        {% render_field form.account_no type="text" name="account_no" id="accountno" class="formbold-form-input" %}
                        {{ form.account_no.errors }}
                    </div>
                    <div id="branchNameSelectDiv" class="d-none">
                        <label class="formbold-form-label">Branch Name</label>
                        <select id="branchDesc" name="branch" class="form-select">
                        </select>
                    </div>
                </div>
                <div class="formbold-input-flex d-none" id="zicb_bank_details">
                    <div>
                        <label class="formbold-form-label">Branch Name</label>
                        <input class="formbold-form-input" id="zicb_branch_name" name="branch" readonly>
                    </div>
                    <div>
                        <label class="formbold-form-label">Sort Code</label>
                        <input class="formbold-form-input" type="text" name="sort_code" maxlength="255" required id="zicb_sort_code">
                    </div>
                </div>
               <!--- <div class="formbold-input-flex d-none" id="sortCodeDiv">
                    <div>
                        <label class="formbold-form-label">Sort Code</label>
                        <input class="formbold-form-input"  name="sort_code" readonly type="text" id="sortcode">
                    </div>
                    <div id="acc" {% if form.account_no.errors %} class="error" {% endif %}>
                        <label class="formbold-form-label">{{ form.account_no.label }} </label>
                        {% render_field form.account_no type="text" name="account_no" id="account_no" class="formbold-form-input" %}
                        {{ form.account_no.errors }}
                    </div>
                </div>-->

                <button class="formbold-btn" id="submit" disabled>Save
                </button>
            </form>
            <!--- <p class="or"></p>
            <form action="{% url 'webapp:upload-bank-details-csv' %}" enctype="multipart/form-data" method="POST">
                {% csrf_token %}
                <div class="formbold-mb-3">
                    <label for="csvupload" class="formbold-form-label">
                        Upload Bank Details as Excel
                    </label>
                    <input
                            type="file"
                            name="csvupload"
                            id="csvupload"
                            class="formbold-form-input"
                    />
                </div>
                <button class="formbold-btn">Upload</button>
                <a href="{% url 'webapp:bank-details-template' %}" class="formbold-btn2">Export Template</a>
            </form>-->
        </div>
    </div>
{% endblock %}

{% block extra-scripts %}
    <script src="{% static 'js/processBankDetails.js' %}"></script>
{% endblock %}

templates/base2.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}">
    <title>{% block title %} {% endblock %}</title>
    {% block styles %}
        <script src="https://kit.fontawesome.com/5b1fb164c9.js" crossorigin="anonymous"></script>
        <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
        <link href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.css" rel="stylesheet"
              type='text/css'>
        <link rel="stylesheet"
              href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.10.5/font/bootstrap-icons.min.css"
              integrity="sha512-ZnR2wlLbSbr8/c9AgLg3jQPAattCUImNsae6NHYnS9KrIwRdcY9DxFotXhNAKIKbAXlRnujIqUWoXXwqyFOeIQ=="
              crossorigin="anonymous" referrerpolicy="no-referrer"/>

        <link rel="stylesheet" href="{% static 'css/main.css' %}">
    {% endblock %}

    {% block extra-styles %}{% endblock %}
</head>
<body>
<div class="shadow rounded">
    <nav class="navbar navbar-secondary " style="background-color: #0B0B45;font-family: 'Roboto Slab',serif;">
        <div class="container">
            <a href="" class="navbar-brand text-white px-2">Infratel-ZICB Payment Integration</a>

            <div>
                <ul class="navbar-nav mr-auto flex-row ">
                    {% if request.user.role == '001' %}
                        <li class="nav-item  p-2"><a href="{% url 'webapp:upload-bank-details' %}"
                                                     class="text-white nav-link">Add Vendor
                            Bank Details</a></li>
                        <li class="nav-item p-2"><a href="{% url 'webapp:bank-details' %}" class="text-white nav-link"
                        >Vendor Bank Details</a></li>
                    {% elif request.user.role == '002' %}
                        <li class="nav-item  p-2"><a href="{% url 'webapp:homepage' %}" class="text-white nav-link"
                        >Transactions</a></li>
                        <li class="nav-item p-2"><a href="{% url 'webapp:transaction-history' %}"
                                                    class="text-white nav-link">Transaction
                            History</a></li>
                    {% endif %}
                    <li class="nav-item dropdown p-2 ">
                        <a class="nav-link dropdown-toggle text-white" href="#"
                           role="button" data-bs-toggle="popover"
                           data-bs-placement="bottom" data-bs-html="true"
                           data-bs-content="<a href='{% url 'webapp:logout' %}' style='text-decoration: none;'>Sign Out</a>"
                        >
                            {{ request.user.username }}</a>

                    </li>

                </ul>

            </div>
        </div>
    </nav>
</div>
{% block content %}{% endblock %}
<footer class="footer pt-5">
    <div class="text-center p-4" >
       Copyright © 2023

    </div>
    <!-- Copyright -->
</footer>
{% block scripts %}
    <script src="https://unpkg.com/htmx.org@1.8.6"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src=" https://cdn.jsdelivr.net/npm/chart.js@4.3.0/dist/chart.umd.min.js "></script>
    <script>
        document.querySelectorAll('.nav-link').forEach(link => {
            if (link.href === window.location.href) {
                link.style.textDecoration = "underline"
            } else {
                link.style.textDecoration = 'none'
            }
        });
        var popoverTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="popover"]'))
        var popoverList = popoverTriggerList.map(function (popoverTriggerEl) {
            return new bootstrap.Popover(popoverTriggerEl)
        })</script>
{% endblock %}

{% block extra-scripts %} {% endblock %}

</body>
</html>

templates/edit-vendor-bank.html
{% extends 'base2.html' %}
{% load static %}
{% load widget_tweaks %}
{% block content %}

    <div class="formbold-main-wrapper">
        {% if messages %}
            {% for message in messages %}
                <p class="text-muted text-center"> {{ message }} </p>
            {% endfor %}
        {% endif %}

        <div class="formbold-form-wrapper">
            <form action="{% url 'webapp:edit-bank-details' acc_id=acc_id %}" method="POST" id="bankDetailsForm">
                {% csrf_token %}
                <div class="formbold-form-title">
                    <h2 class="">Edit Vendor Bank Details</h2>
                </div>
                <div class="formbold-input-flex">
                    <div id="vid" {% if form.vendor_id.errors %} class="error" {% endif %} hx-select="#vid"
                         hx-post="{% url 'webapp:edit-bank-details' acc_id=acc_id %}"
                         hx-trigger="blur from:find input" hx-taget="#vid">
                        <label class="formbold-form-label"> {{ form.vendor_id.label }}</label>
                        {% render_field form.vendor_id type="text" name="vendor_id" id="vendorid" class="formbold-form-input" %}
                        {{ form.vendor_id.errors }}
                    </div>
                    <div id="vname" {% if form.account_name.errors %} class="error" {% endif %} hx-select="#accountname"
                         hx-post="{% url 'webapp:edit-bank-details' acc_id=acc_id %}"
                         hx-trigger="blur from:find input" hx-taget="#accountname">
                        <label class="formbold-form-label"> {{ form.account_name.label }}</label>
                        {% render_field form.account_name type="text" name="account_name" id="accountname" class="formbold-form-input" %}
                        {{ form.account_name.errors }}
                    </div>

                </div>

                <div class="formbold-input-flex">
                    <div id="email" hx-select="#email"
                         hx-post="{% url 'webapp:edit-bank-details' acc_id=acc_id %}"
                         hx-trigger="blur from:find input" hx-taget="#email">
                        <label class="formbold-form-label">{{ form.vendor_email.label }} </label>
                        {% render_field form.vendor_email type="text" name="vendor_email" id="vendoremail" class="formbold-form-input" %}
                        {{ form.vendor_email.errors }}
                    </div>
                    <div id="vmno" hx-select="#vmno" hx-post="{% url 'webapp:edit-bank-details' acc_id=acc_id %}"
                         hx-trigger="blur from:find input" hx-taget="#vmno">
                        <label class="formbold-form-label">{{ form.vendor_mobile_number.label }}</label>
                        {% render_field form.vendor_mobile_number type="text" name="vendor_mobile_no" id="vendorphone" class="formbold-form-input" %}
                        {{ form.vendor_mobile_number.errors }}
                    </div>
                </div>

                <div class="formbold-input-flex" id="bank_dropdown">
                    <div id="acc" {% if form.account_no.errors %} class="error" {% endif %}>
                        <label class="formbold-form-label">{{ form.account_no.label }} </label>
                        {% render_field form.account_no type="text" name="account_no" id="account_no" class="formbold-form-input" %}
                        {{ form.account_no.errors }}
                    </div>
                    <div>
                        <label class="formbold-form-label">Bank Name</label>
                        {% render_field form.bank_name  type="text" name="bank_name" id="bank_name" class="formbold-form-input" %}

                    </div>
                </div>
                <div class="formbold-input-flex " id="zicb_bank_details">
                    <div>
                        <label class="formbold-form-label">Branch Name</label>
                        {% render_field form.branch  type="text" name="branch" id="branch" class="formbold-form-input" %}

                    </div>
                    <div>
                        <label class="formbold-form-label">Sort Code</label>
                        {% render_field form.sort_code  type="text" name="sort_code" id="sort_code" class="formbold-form-input" %}

                    </div>
                </div>
                <!--- <div class="formbold-input-flex d-none" id="sortCodeDiv">
                     <div>
                         <label class="formbold-form-label">Sort Code</label>
                         <input class="formbold-form-input"  name="sort_code" readonly type="text" id="sortcode">
                     </div>

                 </div>-->

                <button class="formbold-btn" id="submit">Save
                </button>
            </form>
            <!--- <p class="or"></p>
            <form action="{% url 'webapp:upload-bank-details-csv' %}" enctype="multipart/form-data" method="POST">
                {% csrf_token %}
                <div class="formbold-mb-3">
                    <label for="csvupload" class="formbold-form-label">
                        Upload Bank Details as Excel
                    </label>
                    <input
                            type="file"
                            name="csvupload"
                            id="csvupload"
                            class="formbold-form-input"
                    />
                </div>
                <button class="formbold-btn">Upload</button>
                <a href="{% url 'webapp:bank-details-template' %}" class="formbold-btn2">Export Template</a>
            </form>-->
        </div>
    </div>
{% endblock %}

{% block extra-scripts %}
{% endblock %}

templates/homepage.html
{% extends 'base2.html' %}
{% load static %}


{% block title %}
    Dashboard
{% endblock %}

{% block content %}
    {% include 'partials/transactions/loader.html' %}
    {% include  'partials/transactions/table.html'%}


{% endblock %}

{% block extra-scripts %}
    <script src="{% static 'js/process_transaction.js' %}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    

{% endblock %}

templates/index.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <title>Login</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}">

    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@7.12.15/dist/sweetalert2.all.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>
<body>

<section class="ftco-section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6 text-center mb-5">
                {% if messages %}
                    {% for message in messages %}
                        <p> {{ message }} </p>
                    {% endfor %}
                {% endif %}
                <h2 class="heading-section"></h2>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-md-7 col-lg-5">
                <div class="login-wrap p-4 p-md-5">
                    <div class="icon d-flex align-items-center justify-content-center">
                        <img src="{% static 'images/infratel_logo.jpg' %}" class="rounded-circle">
                    </div>
                    <h3 class="text-center mb-4">Sign In</h3>
                    <form method="post" class="login-form" id="login-form">
                        {% csrf_token %}
                        <div class="form-group">
                            <input type="text" name="username" id="username" class="form-control rounded-left"
                                   placeholder="Username" required>
                        </div>
                        <div class="form-group">
                            <input type="text" name="cif" class="form-control rounded-left" placeholder="CIF" required>
                        </div>
                        <div class="form-group d-flex">
                            <input type="password" name="password" class="form-control rounded-left"
                                   placeholder="Password" required>
                        </div>
                        <div class="form-group">
                            <a href="{% url 'webapp:login' %}">
                                <button type="submit" id="submit-button"
                                        class="form-control btn rounded submit px-3 text-white"
                                        style="background-color: #0B0B45">Sign In
                                </button>
                            </a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
<script>
    var username = document.getElementById('username');
    var loginSubmit = document.getElementById("submit-button");
    loginSubmit.addEventListener('click', () => {
        fetch(`role/?username=${username.value}`)
            .then(response => response.json())
            .then(resp => {
                console.log(resp.role)
                if (resp.role.role === '002') {
                    swal("OTP Sent");
                }
            })
            .catch(error => {
                // Handle any errors that occurred during the fetch request
                console.error(error);
            });
    })
</script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@7.12.15/dist/sweetalert2.all.min.js"></script>


<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/popper.js' %} "></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>


</body>
</html>

templates/validate-otp.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
  	<title>Validate OTP</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">
<link rel="icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}">

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

	<link rel="stylesheet" href="{% static 'css/style.css' %}">

	</head>
	<body>
	<section class="ftco-section">
		<div class="container">
			<div class="row justify-content-center">

				<div class="col-md-6 text-center mb-5">
                     {% if messages %}
                {% for message in messages %}
               <p> {{ message }} </p>
                {% endfor %}
                {% endif %}
					<h2 class="heading-section"> </h2>
				</div>
			</div>
			<div class="row justify-content-center">
				<div class="col-md-7 col-lg-5">
					<div class="login-wrap p-4 p-md-5">
						<div class="icon d-flex align-items-center justify-content-center">
		      		<img src="{% static 'images/infratel_logo.jpg'%}" class="rounded-circle">
		      			</div>
		      	<h3 class="text-center mb-4">Validate OTP</h3>
						<form  method="post" class="login-form">
							{% csrf_token %}
		      		<div class="form-group">
		      			<input type="text" name="otp" title="OTP is valid for 15 minutes" class="form-control rounded-left" placeholder="Enter OTP" required>
		      		</div>
	            <div class="form-group">
	            	<a href="{% url 'webapp:enter-otp' %}"> <button type="submit" class="form-control btn rounded submit px-3 text-white" style="background-color: #0B0B45">Submit</button> </a>
	            </div>
	            <div class="form-group float-right ">

								<div class="">
									<a href="#">Resend OTP</a>
								</div>
	            </div>
	          </form>
	        </div>
				</div>
			</div>
		</div>
	</section>

	<script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/popper.js' %} "></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/main.js' %}"></script>

	</body>
</html>

templates/vendor-bank-details.html
{% extends 'base2.html' %}
{% load static %}
{% block content %}
    <div class="card p-2">
        <div class="container pt-5">
            <div class="row mb-3 px-2">
                <div class="col pb-5 ">
                    <h3 style="position: absolute;left: 100px;font-weight: 600;font-size: 28px;">AP Vendors</h3>
                    <form style="position: absolute;right: 100px;">
                        <div class="input-group">
                            <input type="text" placeholder="Search by ID" id="vendor-search" name="vendor-search"
                                   class="form-control-sm text-end">
                            <button class="btn text-white" type="button" id="search-button"
                                    style="background-color: #0B0B45;">
                                <i class="fa fa-search"></i>
                            </button>
                        </div>
                    </form>
                </div>
                <table class="table table-hover mt-3" style="table-layout: fixed;">
                    <thead class="text-center" style="font-family: 'Roboto Slab', serif">
                    <tr>
                        <th scope="col">Account No</th>
                        <th scope="col">Account Name</th>
                        <th scope="col">Vendor ID</th>
                        <th scope="col">Vendor Email</th>
                        <th scope="col">Bank Name</th>
                        <th scope="col">Sort Code</th>
                        <th scope="col">Branch Name</th>
                        <th scope="col">Actions</th>
                    </tr>
                    </thead>
                    <tbody class="text-center" id="table-body">
                    {% if bank_details %}
                        {% for details in bank_details %}
                            <tr>
                                <td>{{ details.account_no }}</td>
                                <td>{{ details.account_name }}</td>
                                <td>{{ details.vendor_id }}</td>
                                <td>{{ details.vendor_email }}</td>
                                <td>{{ details.bank_name }}</td>
                                <td id="vendor_acc">{{ details.sort_code }}</td>
                                <td>{{ details.branch }}</td>
                            <td>
                                <a class="btn btn-sm text-white" href="{% url 'webapp:edit-bank-details' acc_id=details.account_no%}" style="background-color: #121271">
                                    Edit
                                </a>
                                <a class="btn btn-dark btn-sm" href="{% url 'webapp:delete' acc_no=details.account_no %}">
                                   Delete
                                </a>
                            </td>
                            </tr>
                        {% endfor %}


                    {% else %}
                        <tr>
                            <td colspan="7" class="py-5">No Vendor Information Found <a
                                    href="{% url 'webapp:upload-bank-details' %}">Add Vendors</a></td>
                        </tr>
                    {% endif %}
                    </tbody>
                </table>
                {% include 'vendor_bank_details_paginator.html' %}
            </div>
        </div>
    </div>
    </div>
{% endblock %}

templates/vendor_bank_details_paginator.html
{% if bank_details.has_other_pages %}
<div class="row paginator-wrap" id="ven-paginator">
  <div class="col-md-6  text-md-left mb-4 mb-md-0">
    <span id="page_navigator">Showing {{ bank_details.number }} of {{ bank_details.paginator.num_pages }} Pages</span>
  </div>
  <div class="col-md-6 text-end">
    <div class="custom-pagination ml-auto">

      <span id="prev_page">
      {% if bank_details.has_previous %}
      <a id="ajax_paginator" href="?page={{ bank_details.previous_page_number }}" class="prev">Prev</a>
      {% endif %}
    </span>
      <span id="page_no">
        <div class="d-inline-block">
          {% for i in bank_details.paginator.page_range %}
          {% if bank_details.number == i %}
          <a id="ajax_paginator" class="ajax_paginator_{{ i }} active" href="?page={{ i }}">{{ i }}</a>

          {% else %}
          <a class="ajax_paginator_{{ i }}" id="ajax_paginator" href="?page={{ i }}">{{ i }}</a>
          {% endif %}
          {% endfor %}
        </div>
      </span>
      {% if bank_details.has_next %}
      <span id="next_page">
        <a id="ajax_paginator" class="next" href="?page={{ bank_details.next_page_number }}">Next</a>
      </span>
      {% endif %}

    </div>
  </div>
</div>
{% endif %}